# C# and .NET Core
# Build and run a C# project with .NET Core 7.0.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  LT_USERNAME: 'ritamg'
  LT_ACCESS_KEY: 'TK7DCf2rFcBJzT3IHz4kD47lThhsHckrlGtiGkYyetAcixtrj5'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '7.x'  # Set the desired .NET SDK version
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .NET SDK'

  - script: |
      dotnet restore
      dotnet build --configuration Release
      dotnet test --configuration Release --no-restore
    displayName: 'Build and Test C# project'
